(cl:defpackage gps_bagger-srv
  (:use )
  (:export
   "WAYPOINTSERVICE"
   "<WAYPOINTSERVICE-REQUEST>"
   "WAYPOINTSERVICE-REQUEST"
   "<WAYPOINTSERVICE-RESPONSE>"
   "WAYPOINTSERVICE-RESPONSE"
   "CALLRESPONSE"
   "<CALLRESPONSE-REQUEST>"
   "CALLRESPONSE-REQUEST"
   "<CALLRESPONSE-RESPONSE>"
   "CALLRESPONSE-RESPONSE"
  ))

