// Generated by gencpp from file gps_bagger/callResponseResponse.msg
// DO NOT EDIT!


#ifndef GPS_BAGGER_MESSAGE_CALLRESPONSERESPONSE_H
#define GPS_BAGGER_MESSAGE_CALLRESPONSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gps_bagger
{
template <class ContainerAllocator>
struct callResponseResponse_
{
  typedef callResponseResponse_<ContainerAllocator> Type;

  callResponseResponse_()
    : response()  {
    }
  callResponseResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::gps_bagger::callResponseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_bagger::callResponseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct callResponseResponse_

typedef ::gps_bagger::callResponseResponse_<std::allocator<void> > callResponseResponse;

typedef boost::shared_ptr< ::gps_bagger::callResponseResponse > callResponseResponsePtr;
typedef boost::shared_ptr< ::gps_bagger::callResponseResponse const> callResponseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps_bagger::callResponseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps_bagger::callResponseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps_bagger::callResponseResponse_<ContainerAllocator1> & lhs, const ::gps_bagger::callResponseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps_bagger::callResponseResponse_<ContainerAllocator1> & lhs, const ::gps_bagger::callResponseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps_bagger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_bagger::callResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_bagger::callResponseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_bagger::callResponseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::gps_bagger::callResponseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps_bagger/callResponseResponse";
  }

  static const char* value(const ::gps_bagger::callResponseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::gps_bagger::callResponseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct callResponseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_bagger::callResponseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps_bagger::callResponseResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_BAGGER_MESSAGE_CALLRESPONSERESPONSE_H
