// Generated by gencpp from file gps_bagger/WaypointServiceRequest.msg
// DO NOT EDIT!


#ifndef GPS_BAGGER_MESSAGE_WAYPOINTSERVICEREQUEST_H
#define GPS_BAGGER_MESSAGE_WAYPOINTSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/NavSatFix.h>

namespace gps_bagger
{
template <class ContainerAllocator>
struct WaypointServiceRequest_
{
  typedef WaypointServiceRequest_<ContainerAllocator> Type;

  WaypointServiceRequest_()
    : waypoints()
    , headings()  {
    }
  WaypointServiceRequest_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)
    , headings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::NavSatFix_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::NavSatFix_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _headings_type;
  _headings_type headings;





  typedef boost::shared_ptr< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointServiceRequest_

typedef ::gps_bagger::WaypointServiceRequest_<std::allocator<void> > WaypointServiceRequest;

typedef boost::shared_ptr< ::gps_bagger::WaypointServiceRequest > WaypointServiceRequestPtr;
typedef boost::shared_ptr< ::gps_bagger::WaypointServiceRequest const> WaypointServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator1> & lhs, const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints &&
    lhs.headings == rhs.headings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator1> & lhs, const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps_bagger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88cdccb45737cfa8f46c03c0226b51dc";
  }

  static const char* value(const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88cdccb45737cfa8ULL;
  static const uint64_t static_value2 = 0xf46c03c0226b51dcULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps_bagger/WaypointServiceRequest";
  }

  static const char* value(const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/NavSatFix[] waypoints\n"
"float64[] headings\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatFix\n"
"# Navigation Satellite fix for any Global Navigation Satellite System\n"
"#\n"
"# Specified using the WGS 84 reference ellipsoid\n"
"\n"
"# header.stamp specifies the ROS time for this measurement (the\n"
"#        corresponding satellite time may be reported using the\n"
"#        sensor_msgs/TimeReference message).\n"
"#\n"
"# header.frame_id is the frame of reference reported by the satellite\n"
"#        receiver, usually the location of the antenna.  This is a\n"
"#        Euclidean frame relative to the vehicle, not a reference\n"
"#        ellipsoid.\n"
"Header header\n"
"\n"
"# satellite fix status information\n"
"NavSatStatus status\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south.\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is west.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid\n"
"# (quiet NaN if no altitude is available).\n"
"float64 altitude\n"
"\n"
"# Position covariance [m^2] defined relative to a tangential plane\n"
"# through the reported position. The components are East, North, and\n"
"# Up (ENU), in row-major order.\n"
"#\n"
"# Beware: this coordinate system exhibits singularities at the poles.\n"
"\n"
"float64[9] position_covariance\n"
"\n"
"# If the covariance of the fix is known, fill it in completely. If the\n"
"# GPS receiver provides the variance of each measurement, put them\n"
"# along the diagonal. If only Dilution of Precision is available,\n"
"# estimate an approximate covariance from that.\n"
"\n"
"uint8 COVARIANCE_TYPE_UNKNOWN = 0\n"
"uint8 COVARIANCE_TYPE_APPROXIMATED = 1\n"
"uint8 COVARIANCE_TYPE_DIAGONAL_KNOWN = 2\n"
"uint8 COVARIANCE_TYPE_KNOWN = 3\n"
"\n"
"uint8 position_covariance_type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatStatus\n"
"# Navigation Satellite fix status for any Global Navigation Satellite System\n"
"\n"
"# Whether to output an augmented fix is determined by both the fix\n"
"# type and the last time differential corrections were received.  A\n"
"# fix is valid when status >= STATUS_FIX.\n"
"\n"
"int8 STATUS_NO_FIX =  -1        # unable to fix position\n"
"int8 STATUS_FIX =      0        # unaugmented fix\n"
"int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation\n"
"int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation\n"
"\n"
"int8 status\n"
"\n"
"# Bits defining which Global Navigation Satellite System signals were\n"
"# used by the receiver.\n"
"\n"
"uint16 SERVICE_GPS =     1\n"
"uint16 SERVICE_GLONASS = 2\n"
"uint16 SERVICE_COMPASS = 4      # includes BeiDou.\n"
"uint16 SERVICE_GALILEO = 8\n"
"\n"
"uint16 service\n"
;
  }

  static const char* value(const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
      stream.next(m.headings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_bagger::WaypointServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps_bagger::WaypointServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::NavSatFix_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
    s << indent << "headings[]" << std::endl;
    for (size_t i = 0; i < v.headings.size(); ++i)
    {
      s << indent << "  headings[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.headings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_BAGGER_MESSAGE_WAYPOINTSERVICEREQUEST_H
